version: '3'
services:
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run --no-autoupdate
    env_file: .env
  fe:
    container_name: smart-reviewer-fe
    image: ghcr.io/martin-nef/smart-reviewer:latest-fe
    environment:
      LOG_LEVEL: debug
      API_URL: "http://be:80"
    restart: unless-stopped
    volumes:
      - ./.thruster:/rails/storage/thruster
  be:
    container_name: smart-reviewer-be
    image: ghcr.io/martin-nef/smart-reviewer:latest-be
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./.thruster:/rails/storage/thruster
